name: IMDB Test Automation

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      
    - name: Start Xvfb (Virtual Display)
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        
    - name: Run tests
      run: |
        export DISPLAY=:99
        ./gradlew clean test --stacktrace --info
      env:
        HEADLESS: true
        CI: true
        selenide.headless: true
        selenide.browser: chrome
        selenide.browserSize: 1920x1080
        
    - name: Generate Allure Report
      if: always()
      run: |
        # Download and setup Allure
        wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
        tar -zxf allure-2.24.0.tgz
        sudo mv allure-2.24.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        
        # Generate report if results exist
        if [ -d "build/allure-results" ]; then
          allure generate build/allure-results --clean -o build/allure-report
        fi
        
    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: build/allure-report/
        retention-days: 30
        
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          build/reports/
          build/test-results/
          build/allure-results/
        retention-days: 30
        if-no-files-found: warn
        
    - name: Upload Screenshots (if any)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: build/screenshots/
        retention-days: 7
        if-no-files-found: ignore